### ISSUE TITLE
Error Reporting

### ISSUE THREAD

**Issue by Zebedeu** [bonus3/woocommerce-points-manager#2]
When deactivating the Woocomerce the theme ceases to function completely.

### Expected behavior

When deactivating Woocommerce the theme should work perfectly

### Real behavior

There is a drastic error, unexpected when you give up the Woocommerce. The Theme that use the Woo Poins Manager plugin will depend on woocommerce to work.

**Comment by bonus3** [comment]
Thank you for reporting. I adjusted the bug.
